# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='clss',
            field=models.ManyToManyField(related_name='spells', to='spellbook.Class'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='component',
            field=models.ManyToManyField(related_name='spells', to='spellbook.Component'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='sub_domain',
            field=models.ManyToManyField(blank=True, related_name='spells', to='spellbook.SubDomain'),
        ),
    ]
