# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0002_auto_20161203_0303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['full_name']},
        ),
    ]
