# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0002_auto_20161205_0448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Clss',
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['sort_val']},
        ),
        migrations.RenameField(
            model_name='component',
            old_name='count',
            new_name='sort_val',
        ),
    ]
