# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0003_auto_20161203_0305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['count']},
        ),
        migrations.AddField(
            model_name='component',
            name='count',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
