# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0004_auto_20161209_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='version',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
