# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CastingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='A lable for URL config', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='A lable for URL config', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='A lable for URL config', max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='A lable for URL config', max_length=20, unique=True)),
                ('link', models.URLField(max_length=255)),
                ('public', models.BooleanField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A lable for URL config', max_length=100, unique=True)),
                ('text', models.TextField()),
                ('ritual', models.BooleanField()),
                ('concentration', models.BooleanField()),
                ('casting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.CastingTime')),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.CharClass')),
            ],
        ),
        migrations.CreateModel(
            name='SpellComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.Component')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.Spell')),
            ],
            options={
                'ordering': ['component'],
            },
        ),
        migrations.CreateModel(
            name='SpellRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='SpellSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=20)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.Source')),
                ('spell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.Spell')),
            ],
            options={
                'ordering': ['source', 'spell'],
            },
        ),
        migrations.AddField(
            model_name='spell',
            name='component',
            field=models.ManyToManyField(related_name='component', through='spellbook_app.SpellComponent', to='spellbook_app.Component'),
        ),
        migrations.AddField(
            model_name='spell',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.Duration'),
        ),
        migrations.AddField(
            model_name='spell',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.Level'),
        ),
        migrations.AddField(
            model_name='spell',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.School'),
        ),
        migrations.AddField(
            model_name='spell',
            name='source',
            field=models.ManyToManyField(related_name='source', through='spellbook_app.SpellSource', to='spellbook_app.Source'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_range',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook_app.SpellRange'),
        ),
    ]
