# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='cast_time_misc',
            new_name='cast_time_sup',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='component_misc',
            new_name='component_sup',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='range_misc',
            new_name='range_sup',
        ),
    ]
