# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook_app', '0002_auto_20161125_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='cast_time_sup',
            new_name='cast_time_text',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='component_sup',
            new_name='component_text',
        ),
        migrations.RenameField(
            model_name='spell',
            old_name='range_sup',
            new_name='range_text',
        ),
        migrations.RemoveField(
            model_name='spell',
            name='source',
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(help_text='A lable for URL config', max_length=1, unique=True),
        ),
    ]
