# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook_app', '0003_auto_20161127_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='cast_time_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='component_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='range_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
