# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook_app', '0004_auto_20161127_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spell',
            options={'ordering': ['level', 'name']},
        ),
    ]
